// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGameToLibrary(arg1:string,arg2:string):Promise<string>;

export function GetAddedLibraries():Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetSteamFeatured():Promise<string>;

export function ModifyConfig(arg1:string,arg2:any):Promise<void>;

export function RemoveGameFromLibrary(arg1:string):Promise<string>;

export function SearchSteamGames(arg1:string):Promise<string>;
