// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGameToLibrary(arg1, arg2) {
  return window['go']['main']['App']['AddGameToLibrary'](arg1, arg2);
}

export function GetAddedLibraries() {
  return window['go']['main']['App']['GetAddedLibraries']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetSteamFeatured() {
  return window['go']['main']['App']['GetSteamFeatured']();
}

export function ModifyConfig(arg1, arg2) {
  return window['go']['main']['App']['ModifyConfig'](arg1, arg2);
}

export function RemoveGameFromLibrary(arg1) {
  return window['go']['main']['App']['RemoveGameFromLibrary'](arg1);
}

export function SearchSteamGames(arg1) {
  return window['go']['main']['App']['SearchSteamGames'](arg1);
}
